import pandas as pd
from pathlib import Path
import finta
import numpy as np

def ta_helper(passed_dataframe, save_label):
    stock_data = passed_dataframe.copy()
    # stock_data['SMA'] = finta.TA.SMA(stock_data)
    # stock_data['SMM'] = finta.TA.SMM(stock_data)
    # stock_data['SSMA'] = finta.TA.SSMA(stock_data)
    # stock_data['EMA'] = finta.TA.EMA(stock_data)
    # stock_data['DEMA'] = finta.TA.DEMA(stock_data)
    # stock_data['TEMA'] = finta.TA.TEMA(stock_data)
    # stock_data['TRIMA'] = finta.TA.TRIMA(stock_data)
    # stock_data['TRIX'] = finta.TA.TRIX(stock_data)
    # stock_data['VAMA'] = finta.TA.VAMA(stock_data)
    # stock_data['ER'] = finta.TA.ER(stock_data)
    # stock_data['KAMA'] = finta.TA.KAMA(stock_data)
    # stock_data['ZLEMA'] = finta.TA.ZLEMA(stock_data)
    # stock_data['WMA'] = finta.TA.WMA(stock_data)
    # stock_data['HMA'] = finta.TA.HMA(stock_data)
    # stock_data['EVWMA'] = finta.TA.EVWMA(stock_data)
    # stock_data['VWAP'] = finta.TA.VWAP(stock_data)
    # stock_data['SMMA'] = finta.TA.SMMA(stock_data)
    # stock_data['FRAMA'] = finta.TA.FRAMA(stock_data)
    # #stock_data['MACD'] = finta.TA.MACD(stock_data)
    # #stock_data['PPO'] = finta.TA.PPO(stock_data)
    # #stock_data['VW_MACD'] = finta.TA.VW_MACD(stock_data)
    # #stock_data['EV_MACD'] = finta.TA.EV_MACD(stock_data)
    # stock_data['MOM'] = finta.TA.MOM(stock_data)
    # stock_data['ROC'] = finta.TA.ROC(stock_data)
    # stock_data['RSI'] = finta.TA.RSI(stock_data)
    # stock_data['IFT_RSI'] = finta.TA.IFT_RSI(stock_data)
    # stock_data['TR'] = finta.TA.TR(stock_data)
    # stock_data['ATR'] = finta.TA.ATR(stock_data)
    # stock_data['SAR'] = finta.TA.SAR(stock_data)
    # #stock_data['BBANDS'] = finta.TA.BBANDS(stock_data)
    # stock_data['BBWIDTH'] = finta.TA.BBWIDTH(stock_data)
    # #stock_data['MOBO'] = finta.TA.MOBO(stock_data)
    # stock_data['PERCENT_B'] = finta.TA.PERCENT_B(stock_data)
    # #stock_data['KC'] = finta.TA.KC(stock_data)
    # #stock_data['DO'] = finta.TA.DO(stock_data)
    # #stock_data['DMI'] = finta.TA.DMI(stock_data)
    # stock_data['ADX'] = finta.TA.ADX(stock_data)
    # #stock_data['PIVOT'] = finta.TA.PIVOT(stock_data)
    # #stock_data['PIVOT_FIB'] = finta.TA.PIVOT_FIB(stock_data)
    # stock_data['STOCH'] = finta.TA.STOCH(stock_data)
    # stock_data['STOCHD'] = finta.TA.STOCHD(stock_data)
    # stock_data['STOCHRSI'] = finta.TA.STOCHRSI(stock_data)
    # stock_data['WILLIAMS'] = finta.TA.WILLIAMS(stock_data)
    # stock_data['UO'] = finta.TA.UO(stock_data)
    # stock_data['AO'] = finta.TA.AO(stock_data)
    # stock_data['MI'] = finta.TA.MI(stock_data)
    # #stock_data['VORTEX'] = finta.TA.VORTEX(stock_data)
    # #stock_data['KST'] = finta.TA.KST(stock_data)
    # #stock_data['TSI'] = finta.TA.TSI(stock_data)
    # stock_data['TP'] = finta.TA.TP(stock_data)
    # stock_data['ADL'] = finta.TA.ADL(stock_data)
    # stock_data['CHAIKIN'] = finta.TA.CHAIKIN(stock_data)
    # stock_data['MFI'] = finta.TA.MFI(stock_data)
    # stock_data['OBV'] = finta.TA.OBV(stock_data)
    # stock_data['WOBV'] = finta.TA.WOBV(stock_data)
    # stock_data['VZO'] = finta.TA.VZO(stock_data)
    # stock_data['PZO'] = finta.TA.PZO(stock_data)
    # stock_data['EFI'] = finta.TA.EFI(stock_data)
    # stock_data['CFI'] = finta.TA.CFI(stock_data)
    # #stock_data['EBBP'] = finta.TA.EBBP(stock_data)
    # stock_data['EMV'] = finta.TA.EMV(stock_data)
    # stock_data['CCI'] = finta.TA.CCI(stock_data)
    # stock_data['COPP'] = finta.TA.COPP(stock_data)
    # #stock_data['BASP'] = finta.TA.BASP(stock_data)
    # #stock_data['BASPN'] = finta.TA.BASPN(stock_data)
    # stock_data['CMO'] = finta.TA.CMO(stock_data)
    # #stock_data['CHANDELIER'] = finta.TA.CHANDELIER(stock_data)
    # stock_data['QSTICK'] = finta.TA.QSTICK(stock_data)
    # #stock_data['TMF'] = finta.TA.TMF(stock_data)
    # #stock_data['WTO'] = finta.TA.WTO(stock_data)
    # stock_data['FISH'] = finta.TA.FISH(stock_data)
    # #stock_data['ICHIMOKU'] = finta.TA.ICHIMOKU(stock_data)
    # #stock_data['APZ'] = finta.TA.APZ(stock_data)
    # stock_data['SQZMI'] = finta.TA.SQZMI(stock_data)
    # stock_data['VPT'] = finta.TA.VPT(stock_data)
    # stock_data['FVE'] = finta.TA.FVE(stock_data)
    # stock_data['VFI'] = finta.TA.VFI(stock_data)
    # stock_data['MSD'] = finta.TA.MSD(stock_data)
    # stock_data['STC'] = finta.TA.STC(stock_data)
    #stock_data['WAVEPM'] = finta.TA.WAVEPM(stock_data)
    stock_data['SMA5'] = finta.TA.SMA(stock_data,5)
    stock_data['SMM5'] = finta.TA.SMM(stock_data,5)
    stock_data['SMA20'] = finta.TA.SMA(stock_data,20)
    stock_data['SMM20'] = finta.TA.SMM(stock_data,20)
    #stock_data['SMA50'] = finta.TA.SMA(stock_data,50)
    #stock_data['SMM50'] = finta.TA.SMM(stock_data,50)
    stock_data['mfi5'] = finta.TA.MFI(stock_data,5)
    stock_data['mfi20'] = finta.TA.MFI(stock_data,20)
    #stock_data['mfi50'] = finta.TA.MFI(stock_data,50)
    stock_data['mom5'] = finta.TA.MOM(stock_data,5)
    stock_data['mom20'] = finta.TA.MOM(stock_data,20)
    #stock_data['mom50'] = finta.TA.MOM(stock_data,50)
    stock_data['rsi5'] = finta.TA.RSI(stock_data,5)
    stock_data['rsi20'] = finta.TA.RSI(stock_data,20)
    #stock_data['rsi50'] = finta.TA.RSI(stock_data,50)
    stock_data['chaikin5'] = finta.TA.CHAIKIN(stock_data,5)
    stock_data['chaikin20'] = finta.TA.CHAIKIN(stock_data,20)
    #stock_data['chaikin50'] = finta.TA.CHAIKIN(stock_data,50)
    #https://www.investopedia.com/top-7-technical-analysis-tools-4773275
    #stock_data['obv'] = finta.TA.OBV(stock_data)
    stock_data['adl'] = finta.TA.ADL(stock_data)
    stock_data['adx5'] = finta.TA.ADX(stock_data,5)
    stock_data['adx20'] = finta.TA.ADX(stock_data,20)
    #stock_data['adx50'] = finta.TA.ADX(stock_data,50)
    #stock_data['macd'] = finta.TA.MACD(stock_data)
    stock_data['stoch'] = finta.TA.STOCH(stock_data)
    #High minus low = new feature (custom loss functions for predictions)
    #window_size = 20
    #window_to_adjust = 'Volume'
    #window_name = window_to_adjust + str(window_size) 
    #stock_data[window_name] = stock_data[window_to_adjust].rolling(window=window_size).mean().pct_change().shift(-window_size)
    stock_data.dropna(inplace = True)
    stock_data['close_change'] = stock_data['Close'].pct_change().shift(-1)
    stock_data['Signal'] = np.where(
    stock_data['close_change'] > 0, 1.0, 0.0)
    # if ticker_list['L.TO']:
    #     l_features_df = stock_data.copy()
    # elif ticker_list['BMO.TO']:
    #     bmo_features_df = stock_data.copy()
    # elif ticker_list['TRI.TO']:
    #     tri_features_df = stock_data.copy()
    # elif ticker_list['CIX.TO']:
    #     cix_features_df = stock_data.copy()
    # full_df = stock_data.copy()
    # for ticker in ticker_list:
    #     ticker_list = {"L.TO":full_df, "BMO.TO":full_df, "TRI.TO": full_df, "CIX.TO": full_df}
    stock_data.to_csv(save_label+".csv")
    return stock_data